### PR TITLE
Component

### PR DESCRIPTION
**Pull request by sarthak-sehgal**
The component page has been created.
Screenshots:
screenshot 1
screenshot 2

### CODE REVIEW

**Comment by sarthak-sehgal** [comment]
@rowlandm, the URL template is: http://139.59.93.32/biojs-frontend/dist/#/component/component_url
You can have a look at some of the components:
1. Cytoscape: http://139.59.93.32/biojs-frontend/dist/#/component/cytoscape
2. Genbank: http://139.59.93.32/biojs-frontend/dist/#/component/genbank

The component_url is created by backend so be careful about this while opening a component's page:
1. There is no special symbol except a hyphen in the URL
2. Slash '/' is replaced with hyphen '-' if it exists in the component's name
For instance, to the component_url is "visallo-cytoscape" for the component "@visallo/cytoscape"

**Comment by rowlandm** [comment]
Thanks Sarthak.

Hey @DennisSchwartz I can see that the current biojs.io is out of date.

Check out cytoscape:
https://github.com/cytoscape/cytoscape.js
http://biojs.io/d/cytoscape
http://139.59.93.32/biojs-frontend/dist/#/component/cytoscape

Github says 3992 commits, 55 contributors, 754 forks, 4352 stars and 211 watching
biojs.io says 3715 commits, 30 contributors, 587 forks,  3673 stars and 195 watching
@Megh-Thakkar data says 3757 commits, 30 contributors, 754 forks, 4352 stars and 4352 watching

Can we get some clarity of why the biojs.io data is incorrect?

@Megh-Thakkar  - can you check your numbers to see why those contributors, watchers might be out? Also it says 561 downloads and the biojs.io says 163,915 downloads.

**Comment by Megh-Thakkar** [comment]
Hi @rowlandm , the number of commits on our end is the one excluding the merge commits, as they are done by Github and not a contributor. Hence, the difference is present.

**Comment by Megh-Thakkar** [comment]
You can have a look at the Github api response [here](https://api.github.com/repos/cytoscape/cytoscape.js). The number of watchers stated is 4352.

**Comment by rowlandm** [comment]
Yeah - I see it. You may have to ask github to fix that bug.

Is it a problem for another component?

**Comment by Megh-Thakkar** [comment]
@rowlandm since the API is uniform, it will be a common problem. Thanks for pointing it out! I will update the data to display the 'Subscriber's Count" for now. We can contact Github for the same.

**Comment by rowlandm** [comment]
We should just check to confirm.

Also put in a request to do more test driven development using components
that may not change often.

**Comment by Megh-Thakkar** [comment]
@rowlandm regarding the number of contributors, the api response can be seen [here](https://api.github.com/repos/cytoscape/cytoscape.js/contributors), which has 30 contributors. Maybe 55 is the number of collaborators.

**Comment by Megh-Thakkar** [comment]
@rowlandm the download data that we have is of github and not npm because the registry api does not provide download data. For example, data of [cytoscape](http://registry.npmjs.com/-/v1/search?text=keywords:biojs,bionode&size=1) from npm.

**Comment by rowlandm** [comment]
Hi @MEGH VIPUL THAKKAR <f2016036@pilani.bits-pilani.ac.in>  - I found this:

https://api.npmjs.org/downloads/point/2017-06-08:2018-06-08/cytoscape

https://github.com/npm/registry/blob/master/docs/download-counts.md

**Comment by rowlandm** [comment]
It came from a stackoverflow post here:
https://stackoverflow.com/questions/34071621/query-npmjs-registry-via-api

**Comment by Megh-Thakkar** [comment]
Hi @rowlandm I had initially pointed it out to use npmjs api but it only returned the top 25 search results from the search and removed the rest, after which I found out about the registry API. In the downloads section as well, they provide a maximum data of the past year.

Hence, I thought to go with the download count from github as it will be up-to-date, even though it is not from npm.

We can discuss this in today's call.

**Comment by Megh-Thakkar** [comment]
@rowlandm @DennisSchwartz is it fine if we go along with download data from github, as the data from npmjs only consists till the past year. Or do we display this data?

**Comment by rowlandm** [comment]
Github download is tiny compared to npm.  I think we go with npm.

**Pull request merged**
