### PR TITLE
Version list

### PR DESCRIPTION
**Pull request by sarthak-sehgal**
I wrote a script to list all the components' versions in the old and the new website and to compare them to produce some useful stats. It's great to see that 91% of the components which are on both the websites have the same version. Screenshot attached (it's too long though!).
screencapture-localhost-8083-2018-07-31-15_35_44

### CODE REVIEW

**Comment by sarthak-sehgal** [comment]
@rowlandm @DennisSchwartz 
Shall I merge this PR?

**Comment by rowlandm** [comment]
I reviewed it  see comments

**Comment by sarthak-sehgal** [comment]
@rowlandm I think I haven't received the comments for this PR.

**Comment by rowlandm** [comment]
Check manually. I think it was this one

**Comment by sarthak-sehgal** [comment]
I can't find the comments manually too. Can you send a screenshot if they're being displayed on your GitHub?

**Comment by rowlandm** [comment]
Sorry - the review was pending for some reason! You should see it now.

**Comment by sarthak-sehgal** [comment]
@rowlandm updated.

**Pull request merged**
