### PR TITLE
Guide page points to biojs EDU website and updated README.md

### LINKED ISSUE #34: Move 'Guide' section to Github
The Guide section of the website is super useful! But mostly for developers working on the front-end. For people trying to learn how to use BioJS components, it's probably not the best start.

I will prepare (or find some old) copy (i.e. content) for the Guide section that will be more helpful for people trying to understand what BioJS actually is :)

For now, let's move this documentation to Github, maybe in the README.md ?

### PR DESCRIPTION
**Pull request by Nikhil-Vats**
All the information on guide page is now shifted to README.md and guide page points to https://edu.biojs.net.
Fixes #34

### CODE REVIEW

**Comment by sarthak-sehgal** [comment]
The guide link should ideally open in a new tab since it is an external link.
Rest of it looks good! Thanks!

**Comment by Nikhil-Vats** [comment]
Thanks for the review, I fixed it. Please verify and proceed.

**Comment by sarthak-sehgal** [comment]
@Nikhil-Vats there seem to be some merge conflicts

**Comment by Nikhil-Vats** [comment]
@sarthak-sehgal There is just one merge conflict now which is the change which was required to solve the issue. I replaced router-link with `a` tag to point the **Guide** link to https://edu.biojs.net/.

**Comment by Nikhil-Vats** [comment]
I have fixed the merge conflict @sarthak-sehgal.

**Pull request merged**
